name: Build and Release

on:
  push:
  workflow_dispatch:

env:
  PACKAGE_NAME: luci-app-xray
  CACHE_DIR: ~/cache

jobs:
  release:
    name: Build for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: mipsel_24kc
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.2/targets/ramips/mt7621
            sdk_name: sdk-24.10.2-ramips-mt7621

    env:
      SDK_URL_PATH: ${{ matrix.sdk_url_path }}
      SDK_NAME: ${{ matrix.sdk_name }}
      CCACHE_DIR: ~/.ccache
      CONFIG_CCACHE: y
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Cache Key
        id: cache_key
        run: echo "::set-output name=timestamp::$(date +"%s")"

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.CACHE_DIR }}
            ${{ env.CCACHE_DIR }}
          key: openwrt-${{ matrix.arch }}-${{ env.PACKAGE_NAME }}-${{ steps.cache_key.outputs.timestamp }}
          restore-keys: |
            openwrt-${{ matrix.arch }}-${{ env.PACKAGE_NAME }}-
      - name: Install Dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y ccache gettext libncurses5-dev xsltproc p7zip-full
      - name: Create Directories
        run: |
          CACHE_DIR_SDK="$(eval echo "$CACHE_DIR/sdk")"
          CACHE_DIR_DL="$(eval echo "$CACHE_DIR/dl")"
          CACHE_DIR_FEEDS="$(eval echo "$CACHE_DIR/feeds")"
          echo "CACHE_DIR_SDK: $CACHE_DIR_SDK"
          echo "CACHE_DIR_DL: $CACHE_DIR_DL"
          echo "CACHE_DIR_FEEDS: $CACHE_DIR_FEEDS"
          test -d "$CACHE_DIR_SDK" || mkdir -p "$CACHE_DIR_SDK"
          test -d "$CACHE_DIR_DL" || mkdir -p "$CACHE_DIR_DL"
          test -d "$CACHE_DIR_FEEDS" || mkdir -p "$CACHE_DIR_FEEDS"
          echo "CACHE_DIR_SDK=$CACHE_DIR_SDK" >> $GITHUB_ENV
          echo "CACHE_DIR_DL=$CACHE_DIR_DL" >> $GITHUB_ENV
          echo "CACHE_DIR_FEEDS=$CACHE_DIR_FEEDS" >> $GITHUB_ENV
          echo "SDK_HOME=$(mktemp -d)" >> $GITHUB_ENV
      - name: Download and Verify SDK
        run: |
          cd "$CACHE_DIR_SDK"
          if ! ( wget -q -O - "$SDK_URL_PATH/sha256sums" | grep -- "$SDK_NAME" > sha256sums.small 2>/dev/null ) ; then
            echo "::error::Can not find ${SDK_NAME} file in sha256sums."
            exit 1
          fi
          SDK_FILE="$(cat sha256sums.small | cut -d' ' -f2 | sed 's/*//g')"
          # Проверяем, есть ли уже файл и совпадает ли его хеш-сумма
          if ! sha256sum -c ./sha256sums.small >/dev/null 2>&1 ; then
            echo "SDK not found or checksum mismatch. Downloading..."
            wget -q -O "$SDK_FILE" "$SDK_URL_PATH/$SDK_FILE"
            # Повторная проверка после скачивания
            if ! sha256sum -c ./sha256sums.small >/dev/null 2>&1 ; then
              echo "::error::SDK can not be verified after download!"
              exit 1
            fi
          else
            echo "SDK found in cache and checksum is valid."
          fi
          # Сохраняем имя файла для следующих шагов
          echo "SDK_FILE=$SDK_FILE" >> $GITHUB_ENV
          cd -

      - name: Extract SDK
        run: |
          echo "Extracting SDK file: ${{ env.CACHE_DIR_SDK }}/${{ env.SDK_FILE }}"
          file "${{ env.CACHE_DIR_SDK }}/${{ env.SDK_FILE }}"
          7z x "${{ env.CACHE_DIR_SDK }}/${{ env.SDK_FILE }}" -so | tar -C "$SDK_HOME" -xvf - --strip=1
          echo "SDK extracted to ${{ env.SDK_HOME }}"

      - name: Link Cache Directories
        working-directory: ${{ env.SDK_HOME }}
        run: |
          # Удаляем стандартные папки, если они есть
          test -d "dl" && rm -rf "dl" || true
          test -d "feeds" && rm -rf "feeds" || true
          # Создаем симлинки на кешированные папки
          ln -s "$CACHE_DIR_DL" "dl"
          ln -s "$CACHE_DIR_FEEDS" "feeds"
          echo "Cache directories linked."

      - name: Configure Feeds
        working-directory: ${{ env.SDK_HOME }}
        run: |
          cp feeds.conf.default feeds.conf
          sed -i 's#git.openwrt.org/openwrt/openwrt#github.com/openwrt/openwrt#' feeds.conf
          sed -i 's#git.openwrt.org/feed/packages#github.com/openwrt/packages#' feeds.conf
          sed -i 's#git.openwrt.org/project/luci#github.com/openwrt/luci#' feeds.conf
          sed -i 's#git.openwrt.org/feed/telephony#github.com/openwrt/telephony#' feeds.conf
          echo "Feeds configured to use GitHub mirrors."
      - name: Update and Install Packages
        run: |
          cd "$SDK_HOME"
          ./scripts/feeds update -a
          ln -s "${{ github.workspace }}" "package/$PACKAGE_NAME"
          ./scripts/feeds install -a
          cd -
      - name: Build Packages
        run: |
          cd "$SDK_HOME"
          make defconfig
          make package/${PACKAGE_NAME}/status/{clean,compile} V=s
          find "$SDK_HOME/bin/" -type f -name "*.ipk" -exec ls -lh {} \;
          cd -
      - name: Copy Bin Files
        run: |
          find "$SDK_HOME/bin/" -type f -name "${PACKAGE_NAME}*.ipk" -exec cp {} "${{ github.workspace }}" \;
          find "${{ github.workspace }}" -type f -name "*.ipk" -exec ls -lh {} \;
      - name: Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: "*.ipk"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
